// Item and weapon text patches  -- names, descriptions, and stats for
// every weapon, outfit, antenna, accessory, and treasure in the game.
//
// MainRow layout (80 entries, 0-indexed):
//
//	0-22   Weapons (Arm MG through Magoroku)
//	23-33  Ammo types
//	34-50  Outfits
//	51-68  Antennas and accessories
//	69-71  Treasures
//	72-76  Voice kits
//	77-79  Lift batteries
//
// Each field is a *string  -- nil means "keep the original Japanese text."
// Use strptr() (in item.go) to create inline string pointers.
//
// The mainRowToItemListRow map in item.go translates main table rows to
// their corresponding item list rows (the two BSV tables have different
// orderings).

package main

var itemPatches = []ItemTextPatch{
	{
		MainRow:     0,
		Name:        strptr("Arm MG"),
		Info1:       strptr("Range C"),
		Info2:       strptr("Power C"),
		Info3:       strptr(""),
		Description: strptr("Cheap, simple machine gun."),
	},
	{
		MainRow:     1,
		Name:        strptr("Needler"),
		Info1:       strptr("Range B"),
		Info2:       strptr("Power D"),
		Info3:       strptr(""),
		Description: strptr("Fires explosive arrows in straight lines."),
	},
	{
		MainRow:     2,
		Name:        strptr("HMG"),
		Info1:       strptr("Range C"),
		Info2:       strptr("Power B"),
		Info3:       strptr(""),
		Description: strptr("Rapid-fire destructive power."),
	},
	{
		MainRow:     3,
		Name:        strptr("Handgun"),
		Info1:       strptr("Range C"),
		Info2:       strptr("Power E"),
		Info3:       strptr(""),
		Description: strptr("Semi-automatic."),
	},
	{
		MainRow:     4,
		Name:        strptr("Sniper"),
		Info1:       strptr("Range A"),
		Info2:       strptr("Power B"),
		Info3:       strptr(""),
		Description: strptr("Effective at long range."),
	},
	{
		MainRow:     5,
		Name:        strptr("SMG"),
		Info1:       strptr("Range C"),
		Info2:       strptr("Power D"),
		Info3:       strptr(""),
		Description: strptr("Easy handling, medium rate of fire."),
	},
	{
		MainRow:     6,
		Name:        strptr("Bazooka"),
		Info1:       strptr("Range C"),
		Info2:       strptr("Power A"),
		Info3:       strptr(""),
		Description: strptr("Lock-on heavy weapon."),
	},
	{
		MainRow:     7,
		Name:        strptr("Faust"),
		Info1:       strptr("Range B"),
		Info2:       strptr("Power A"),
		Info3:       strptr(""),
		Description: strptr("Large muzzle flash."),
	},
	{
		MainRow:     8,
		Name:        strptr("Missile"),
		Info1:       strptr("Range B"),
		Info2:       strptr("Power A"),
		Info3:       strptr(""),
		Description: strptr("Fires 3 lock-on missiles at once."),
	},
	{
		MainRow:     9,
		Name:        strptr("Revolver"),
		Info1:       strptr("Range D"),
		Info2:       strptr("Power B"),
		Info3:       strptr(""),
		Description: strptr("Speedloader included."),
	},
	{
		MainRow:     10,
		Name:        strptr("Shotgun"),
		Info1:       strptr("Range D"),
		Info2:       strptr("Power B"),
		Info3:       strptr(""),
		Description: strptr("Wide spread, short range."),
	},
	{
		MainRow:     11,
		Name:        strptr("Flail"),
		Info1:       strptr("Melee"),
		Info2:       strptr("Power A"),
		Info3:       strptr("Combo 1"),
		Description: strptr("Die-cast metal. Slow but powerful."),
	},
	{
		MainRow:     12,
		Name:        strptr("Swat"),
		Info1:       strptr("Melee"),
		Info2:       strptr("Power D"),
		Info3:       strptr("Combo 1"),
		Description: strptr("Wide upper-front attack for anti-air."),
	},
	{
		MainRow:     13,
		Name:        strptr("Izayoi"),
		Info1:       strptr("Melee"),
		Info2:       strptr("Power B"),
		Info3:       strptr("Combo 3"),
		Description: strptr("Extremely sharp titanium blade."),
	},
	{
		MainRow:     14,
		Name:        strptr("Kotetsu"),
		Info1:       strptr("Melee"),
		Info2:       strptr("Power C"),
		Info3:       strptr("Combo 3"),
		Description: strptr("Carbon steel blade."),
	},
	{
		MainRow:     15,
		Name:        strptr("Magoroku"),
		Info1:       strptr("Melee"),
		Info2:       strptr("Power D"),
		Info3:       strptr("Combo 3"),
		Description: strptr("Ceramic blade."),
	},
	{
		MainRow:     16,
		Name:        strptr("Hoihoihawk"),
		Info1:       strptr("Melee"),
		Info2:       strptr("Power C"),
		Info3:       strptr("Combo 1"),
		Description: strptr("Attack with a spin."),
	},
	{
		MainRow:     17,
		Name:        strptr("S.Knuckle"),
		Info1:       strptr("Melee"),
		Info2:       strptr("Power B"),
		Info3:       strptr("Combo 1"),
		Description: strptr("Rapid crusher drill. Effective on nests."),
	},
	{
		MainRow:     18,
		Name:        strptr("Javelin"),
		Info1:       strptr("Melee"),
		Info2:       strptr("Power C"),
		Info3:       strptr("Combo 1"),
		Description: strptr("Polearm with a short lunge."),
	},
	{
		MainRow:     19,
		Name:        strptr("Onusa"),
		Info1:       strptr("Melee"),
		Info2:       strptr("Power ?"),
		Info3:       strptr("Combo ?"),
		Description: strptr("Purification wand."),
	},
	{
		MainRow:     20,
		Name:        strptr("Magic Wand"),
		Info1:       strptr("Melee"),
		Info2:       strptr("Power E"),
		Info3:       strptr("Combo 3"),
		Description: strptr("Ceramic. Makes a sound."),
	},
	{
		MainRow:     21,
		Name:        strptr("Tessen"),
		Info1:       strptr("Melee"),
		Info2:       strptr("Power D"),
		Info3:       strptr("Combo 3"),
		Description: strptr("Carbon steel cutting edge."),
	},
	{
		MainRow:     22,
		Name:        strptr("Excalibur"),
		Info1:       strptr("Melee"),
		Info2:       strptr("Power A"),
		Info3:       strptr("Combo 3"),
		Description: strptr("Unwieldy titanium blade."),
	},
// Ammo 23-33
	{
		MainRow:     23,
		Name:        strptr("Amm.Arm MG"),
		Info1:       strptr("Ammo"),
		Info2:       strptr(""),
		Info3:       strptr(""),
		Description: strptr("20 round mag."),
	},
	{
		MainRow:     24,
		Name:        strptr("Amm.Needler"),
		Info1:       strptr("Ammo"),
		Info2:       strptr(""),
		Info3:       strptr(""),
		Description: strptr("10 charge mag."),
	},
	{
		MainRow:     25,
		Name:        strptr("Amm.HMG"),
		Info1:       strptr("Ammo"),
		Info2:       strptr(""),
		Info3:       strptr(""),
		Description: strptr("60 round double-mag."),
	},
	{
		MainRow:     26,
		Name:        strptr("Amm.Handgun"),
		Info1:       strptr("Ammo"),
		Info2:       strptr(""),
		Info3:       strptr(""),
		Description: strptr("10 round mag."),
	},
	{
		MainRow:     27,
		Name:        strptr("Amm.Sniper"),
		Info1:       strptr("Ammo"),
		Info2:       strptr(""),
		Info3:       strptr(""),
		Description: strptr("5 round mag."),
	},
	{
		MainRow:     28,
		Name:        strptr("Amm.SMG"),
		Info1:       strptr("Ammo"),
		Info2:       strptr(""),
		Info3:       strptr(""),
		Description: strptr("20 round mag."),
	},
	{
		MainRow:     29,
		Name:        strptr("Amm.Bazooka"),
		Info1:       strptr("Ammo"),
		Info2:       strptr(""),
		Info3:       strptr(""),
		Description: strptr("5 round mag."),
	},
	{
		MainRow:     30,
		Name:        strptr("Amm.Faust"),
		Info1:       strptr("Ammo"),
		Info2:       strptr(""),
		Info3:       strptr(""),
		Description: strptr("3 round mag."),
	},
	{
		MainRow:     31,
		Name:        strptr("Amm.Missile"),
		Info1:       strptr("Ammo"),
		Info2:       strptr(""),
		Info3:       strptr(""),
		Description: strptr("3 round mag."),
	},
	{
		MainRow:     32,
		Name:        strptr("Amm.Revolver"),
		Info1:       strptr("Ammo"),
		Info2:       strptr(""),
		Info3:       strptr(""),
		Description: strptr("6 round speedloader."),
	},
	{
		MainRow:     33,
		Name:        strptr("Amm.Shotgun"),
		Info1:       strptr("Ammo"),
		Info2:       strptr(""),
		Info3:       strptr(""),
		Description: strptr("7 shotgun rounds."),
	},
	{
// Outfits 34-50
		MainRow:     34,
		Name:        strptr("Maid"),
		Info1:       strptr("Outfit"),
		Info2:       strptr(""),
		Info3:       strptr(""),
		Description: strptr("Standard-issue maid outfit."),
	},
	{
		MainRow:     35,
		Name:        strptr("Santa"),
		Info1:       strptr("Outfit"),
		Info2:       strptr("Unequips"),
		Info3:       strptr("headwear."),
		Description: strptr("Christmas outfit. Includes hat."),
	},
	{
		MainRow:     36,
		Name:        strptr("Swimsuit"),
		Info1:       strptr("Outfit"),
		Info2:       strptr(""),
		Info3:       strptr(""),
		Description: strptr(""),
	},
	{
		MainRow:     37,
		Name:        strptr("Waitress"),
		Info1:       strptr("Outfit"),
		Info2:       strptr(""),
		Info3:       strptr(""),
		Description: strptr("Includes tray and waitress cap."),
	},
	{
		MainRow:     38,
		Name:        strptr("Gym Clothes"),
		Info1:       strptr("Outfit"),
		Info2:       strptr(""),
		Info3:       strptr(""),
		Description: strptr(""),
	},
	{
		MainRow:     39,
		Name:        strptr("Gothic Dress"),
		Info1:       strptr("Outfit"),
		Info2:       strptr(""),
		Info3:       strptr(""),
		Description: strptr("A handmade dress from Kimiko."),
	},
	{
		MainRow:     40,
		Name:        strptr("Magic Dress"),
		Info1:       strptr("Outfit"),
		Info2:       strptr("Unequips"),
		Info3:       strptr("headwear."),
		Description: strptr("Wizard outfit, with hat."),
	},
	{
		MainRow:     41,
		Name:        strptr("Military"),
		Info1:       strptr("Outfit"),
		Info2:       strptr(""),
		Info3:       strptr(""),
		Description: strptr("Camouflaged outfit with military boots."),
	},
	{
		MainRow:     42,
		Name:        strptr("Fantasy"),
		Info1:       strptr("Outfit"),
		Info2:       strptr("Unequips"),
		Info3:       strptr("headwear."),
		Description: strptr("A fantasy warrior outfit."),
	},
	{
		MainRow:     43,
		Name:        strptr("M. RED"),
		Info1:       strptr("Outfit"),
		Info2:       strptr(""),
		Info3:       strptr(""),
		Description: strptr("MIRAGE RED ~ A colorful outfit."),
	},
	{
		MainRow:     44,
		Name:        strptr("W. BLUE"),
		Info1:       strptr("Outfit"),
		Info2:       strptr(""),
		Info3:       strptr(""),
		Description: strptr("WONDER BLUE ~ A colorful outfit."),
	},
	{
		MainRow:     45,
		Name:        strptr("S. ORANGE"),
		Info1:       strptr("Outfit"),
		Info2:       strptr(""),
		Info3:       strptr(""),
		Description: strptr("STOIC ORANGE ~ A colorful outfit."),
	},
	{
		MainRow:     46,
		Name:        strptr("I. PURPLE"),
		Info1:       strptr("Outfit"),
		Info2:       strptr(""),
		Info3:       strptr(""),
		Description: strptr("ILLUSION PURPLE ~ A colorful outfit."),
	},
	{
		MainRow:     47,
		Name:        strptr("T. BLACK"),
		Info1:       strptr("Outfit"),
		Info2:       strptr(""),
		Info3:       strptr(""),
		Description: strptr("TURN BLACK ~ A colorful outfit."),
	},
	{
		MainRow:     48,
		Name:        strptr("Furisode"),
		Info1:       strptr("Outfit"),
		Info2:       strptr("Disables"),
		Info3:       strptr("missions."),
		Description: strptr("New Year's outfit. You can't play missions while wearing this."),
	},
	{
		MainRow:     49,
		Name:        strptr("Miko"),
		Info1:       strptr("Outfit"),
		Info2:       strptr(""),
		Info3:       strptr(""),
		Description: strptr("Includes onusa and bamboo broom."),
	},
	{
		MainRow:     50,
		Name:        strptr("Chinese"),
		Info1:       strptr("Outfit"),
		Info2:       strptr("Disables"),
		Info3:       strptr("missions."),
		Description: strptr("You can't play missions while wearing this."),
	},
	{
		MainRow:     51,
// Antennas & accessories 51-68
		Name:        strptr("Antenna"),
		Info1:       strptr("Antenna"),
		Info2:       strptr(""),
		Info3:       strptr(""),
		Description: strptr("Standard antenna."),
	},
	{
		MainRow:     52,
		Name:        strptr("Broom"),
		Info1:       strptr("Item"),
		Info2:       strptr(""),
		Info3:       strptr(""),
		Description: strptr("Cleaning broom."),
	},
	{
		MainRow:     53,
		Name:        strptr("Voice Kit"),
		Info1:       strptr("Antenna"),
		Info2:       strptr(""),
		Info3:       strptr(""),
		Description: strptr("Talking Hoihoi-san."),
	},
	{
		MainRow:     54,
		Name:        strptr("VK: Cool"),
		Info1:       strptr("Antenna"),
		Info2:       strptr(""),
		Info3:       strptr(""),
		Description: strptr("Cool voice."),
	},
	{
		MainRow:     55,
		Name:        strptr("VK: Onee-san"),
		Info1:       strptr("Antenna"),
		Info2:       strptr(""),
		Info3:       strptr(""),
		Description: strptr("Older sister voice."),
	},
	{
		MainRow:     56,
		Name:        strptr("VK: Kansai"),
		Info1:       strptr("Antenna"),
		Info2:       strptr(""),
		Info3:       strptr(""),
		Description: strptr("Kansai dialect."),
	},
	{
		MainRow:     57,
		Name:        strptr("VK: Heroine"),
		Info1:       strptr("Antenna"),
		Info2:       strptr(""),
		Info3:       strptr(""),
		Description: strptr("Heroine voice."),
	},
	{
		MainRow:     58,
		Name:        strptr("Analysystem"),
		Info1:       strptr("Antenna"),
		Info2:       strptr(""),
		Info3:       strptr(""),
		Description: strptr("Adds analysis function to check target state."),
	},
	{
		MainRow:     59,
		Name:        strptr("HVA System"),
		Info1:       strptr("Antenna"),
		Info2:       strptr(""),
		Info3:       strptr(""),
		Description: strptr("Hyper Vital Assist w/ Anti-Vibration and Analyze System."),
	},
	{
		MainRow:     60,
		Name:        strptr("Bat.pack S"),
		Info1:       strptr("Auxiliary"),
		Info2:       strptr(""),
		Info3:       strptr(""),
		Description: strptr("Backpack with 2 expansion batteries."),
	},
	{
		MainRow:     61,
		Name:        strptr("Bat.pack M"),
		Info1:       strptr("Auxiliary"),
		Info2:       strptr(""),
		Info3:       strptr(""),
		Description: strptr("Backpack with 4 expansion batteries."),
	},
	{
		MainRow:     62,
		Name:        strptr("Bat.pack L"),
		Info1:       strptr("Auxiliary"),
		Info2:       strptr(""),
		Info3:       strptr(""),
		Description: strptr("Backpack with 6 expansion batteries."),
	},
	{
		MainRow:     63,
		Name:        strptr("Desk Charger"),
		Info1:       strptr("Installed"),
		Info2:       strptr(""),
		Info3:       strptr(""),
		Description: strptr("Included charger dock."),
	},
	{
		MainRow:     64,
		Name:        strptr("Mobile Lift"),
		Info1:       strptr("Installed"),
		Info2:       strptr(""),
		Info3:       strptr(""),
		Description: strptr("Made of ABS; lightweight but strong."),
	},
	{
		MainRow:     65,
		Name:        strptr("Glasses"),
		Info1:       strptr("Accessory"),
		Info2:       strptr(""),
		Info3:       strptr(""),
		Description: strptr(""),
	},
	{
		MainRow:     66,
		Name:        strptr("Sunglasses"),
		Info1:       strptr("Accessory"),
		Info2:       strptr(""),
		Info3:       strptr(""),
		Description: strptr(""),
	},
	{
		MainRow:     67,
		Name:        strptr("Cat Ears"),
		Info1:       strptr("Accessory"),
		Info2:       strptr(""),
		Info3:       strptr(""),
		Description: strptr(""),
	},
	{
		MainRow:     68,
		Name:        strptr("Rabbit Ears"),
		Info1:       strptr("Accessory"),
		Info2:       strptr(""),
		Info3:       strptr(""),
		Description: strptr(""),
	},
	{
		MainRow:     69,
		Name:        strptr("Voice Player"),
// Treasures 69-71
		Info1:       strptr("Treasure"),
		Info2:       strptr(""),
		Info3:       strptr(""),
		Description: strptr("Play the voice of Talking Hoihoi-san at will."),
	},
	{
		MainRow:     70,
		Name:        strptr("Puzzle"),
		Info1:       strptr("Treasure"),
		Info2:       strptr(""),
		Info3:       strptr(""),
		Description: strptr("???"),
	},
	{
		MainRow:     71,
		Name:        strptr("Point Card"),
		Info1:       strptr("Treasure"),
		Info2:       strptr(""),
		Info3:       strptr(""),
		Description: strptr("Sticker sheet for pharmacy points."),
	},
	{
		MainRow:     72,
		Name:        strptr("Voice Kit"),
		Info1:       strptr("Press □"),
// Voice kits 72-76
		Info2:       strptr("to play"),
		Info3:       strptr("audio."),
		Description: strptr("Talking Hoihoi-san."),
	},
	{
		MainRow:     73,
		Name:        strptr("Voice (Cool)"),
		Info1:       strptr("Press □"),
		Info2:       strptr("to play"),
		Info3:       strptr("audio."),
		Description: strptr("Cool voice."),
	},
	{
		MainRow:     74,
		Name:        strptr("Voice (Onee-san)"),
		Info1:       strptr("Press □"),
		Info2:       strptr("to play"),
		Info3:       strptr("audio."),
		Description: strptr("Older sister voice."),
	},
	{
		MainRow:     75,
		Name:        strptr("Voice (Kansai)"),
		Info1:       strptr("Press □"),
		Info2:       strptr("to play"),
		Info3:       strptr("audio."),
		Description: strptr("Kansai dialect."),
	},
	{
		MainRow:     76,
		Name:        strptr("Voice (Heroine)"),
		Info1:       strptr("Press □"),
		Info2:       strptr("to play"),
		Info3:       strptr("audio."),
		Description: strptr("Heroine voice."),
	},
	{
		MainRow:     77,
		Name:        strptr("R Lift Bat."),
		Info1:       strptr("Installed"),
		Info2:       strptr("Enables"),
// Lift batteries 77-79
		Info3:       strptr("red lift."),
		Description: strptr("Battery for red Mobile Lift."),
	},
	{
		MainRow:     78,
		Name:        strptr("G Lift Bat."),
		Info1:       strptr("Installed"),
		Info2:       strptr("Enables"),
		Info3:       strptr("green lift."),
		Description: strptr("Battery for green Mobile Lift."),
	},
	{
		MainRow:     79,
		Name:        strptr("B Lift Bat."),
		Info1:       strptr("Installed"),
		Info2:       strptr("Enables"),
		Info3:       strptr("blue lift."),
		Description: strptr("Battery for blue Mobile Lift."),
	},
}
