// Item and weapon text patches  -- names, descriptions, and stats for
// every weapon, outfit, antenna, accessory, and treasure in the game.
//
// MainRow layout (80 entries, 0-indexed):
//
//	0-22   Weapons (Arm MG through Magoroku)
//	23-33  Ammo types
//	34-50  Outfits
//	51-68  Antennas and accessories
//	69-71  Treasures
//	72-76  Voice kits
//	77-79  Lift batteries
//
// Each field is a *string  -- nil means "keep the original Japanese text."
// Use StrPtr() (in item.go) to create inline string pointers.
//
// The mainRowToItemListRow map in item.go translates main table rows to
// their corresponding item list rows (the two BSV tables have different
// orderings).

package text

var Items = []ItemTextPatch{
	{
		MainRow:     0,
		Name:        StrPtr("Arm MG"),
		Info1:       StrPtr("Range C"),
		Info2:       StrPtr("Power C"),
		Info3:       StrPtr(""),
		Description: StrPtr("Cheap, simple machine gun."),
	},
	{
		MainRow:     1,
		Name:        StrPtr("Needler"),
		Info1:       StrPtr("Range B"),
		Info2:       StrPtr("Power D"),
		Info3:       StrPtr(""),
		Description: StrPtr("Fires explosive arrows in straight lines."),
	},
	{
		MainRow:     2,
		Name:        StrPtr("HMG"),
		Info1:       StrPtr("Range C"),
		Info2:       StrPtr("Power B"),
		Info3:       StrPtr(""),
		Description: StrPtr("Rapid-fire destructive power."),
	},
	{
		MainRow:     3,
		Name:        StrPtr("Handgun"),
		Info1:       StrPtr("Range C"),
		Info2:       StrPtr("Power E"),
		Info3:       StrPtr(""),
		Description: StrPtr("Semi-automatic."),
	},
	{
		MainRow:     4,
		Name:        StrPtr("Sniper"),
		Info1:       StrPtr("Range A"),
		Info2:       StrPtr("Power B"),
		Info3:       StrPtr(""),
		Description: StrPtr("Effective at long range."),
	},
	{
		MainRow:     5,
		Name:        StrPtr("SMG"),
		Info1:       StrPtr("Range C"),
		Info2:       StrPtr("Power D"),
		Info3:       StrPtr(""),
		Description: StrPtr("Easy handling, medium rate of fire."),
	},
	{
		MainRow:     6,
		Name:        StrPtr("Bazooka"),
		Info1:       StrPtr("Range C"),
		Info2:       StrPtr("Power A"),
		Info3:       StrPtr(""),
		Description: StrPtr("Lock-on heavy weapon."),
	},
	{
		MainRow:     7,
		Name:        StrPtr("Faust"),
		Info1:       StrPtr("Range B"),
		Info2:       StrPtr("Power A"),
		Info3:       StrPtr(""),
		Description: StrPtr("Large muzzle flash."),
	},
	{
		MainRow:     8,
		Name:        StrPtr("Missile"),
		Info1:       StrPtr("Range B"),
		Info2:       StrPtr("Power A"),
		Info3:       StrPtr(""),
		Description: StrPtr("Fires 3 lock-on missiles at once."),
	},
	{
		MainRow:     9,
		Name:        StrPtr("Revolver"),
		Info1:       StrPtr("Range D"),
		Info2:       StrPtr("Power B"),
		Info3:       StrPtr(""),
		Description: StrPtr("Speedloader included."),
	},
	{
		MainRow:     10,
		Name:        StrPtr("Shotgun"),
		Info1:       StrPtr("Range D"),
		Info2:       StrPtr("Power B"),
		Info3:       StrPtr(""),
		Description: StrPtr("Wide spread, short range."),
	},
	{
		MainRow:     11,
		Name:        StrPtr("Flail"),
		Info1:       StrPtr("Melee"),
		Info2:       StrPtr("Power A"),
		Info3:       StrPtr("Combo 1"),
		Description: StrPtr("Die-cast metal. Slow but powerful."),
	},
	{
		MainRow:     12,
		Name:        StrPtr("Swat"),
		Info1:       StrPtr("Melee"),
		Info2:       StrPtr("Power D"),
		Info3:       StrPtr("Combo 1"),
		Description: StrPtr("Wide upper-front attack for anti-air."),
	},
	{
		MainRow:     13,
		Name:        StrPtr("Izayoi"),
		Info1:       StrPtr("Melee"),
		Info2:       StrPtr("Power B"),
		Info3:       StrPtr("Combo 3"),
		Description: StrPtr("Extremely sharp titanium blade."),
	},
	{
		MainRow:     14,
		Name:        StrPtr("Kotetsu"),
		Info1:       StrPtr("Melee"),
		Info2:       StrPtr("Power C"),
		Info3:       StrPtr("Combo 3"),
		Description: StrPtr("Carbon steel blade."),
	},
	{
		MainRow:     15,
		Name:        StrPtr("Magoroku"),
		Info1:       StrPtr("Melee"),
		Info2:       StrPtr("Power D"),
		Info3:       StrPtr("Combo 3"),
		Description: StrPtr("Ceramic blade."),
	},
	{
		MainRow:     16,
		Name:        StrPtr("Hoihoihawk"),
		Info1:       StrPtr("Melee"),
		Info2:       StrPtr("Power C"),
		Info3:       StrPtr("Combo 1"),
		Description: StrPtr("Attack with a spin."),
	},
	{
		MainRow:     17,
		Name:        StrPtr("S.Knuckle"),
		Info1:       StrPtr("Melee"),
		Info2:       StrPtr("Power B"),
		Info3:       StrPtr("Combo 1"),
		Description: StrPtr("Rapid crusher drill. Effective on nests."),
	},
	{
		MainRow:     18,
		Name:        StrPtr("Javelin"),
		Info1:       StrPtr("Melee"),
		Info2:       StrPtr("Power C"),
		Info3:       StrPtr("Combo 1"),
		Description: StrPtr("Polearm with a short lunge."),
	},
	{
		MainRow:     19,
		Name:        StrPtr("Onusa"),
		Info1:       StrPtr("Melee"),
		Info2:       StrPtr("Power ?"),
		Info3:       StrPtr("Combo ?"),
		Description: StrPtr("Purification wand."),
	},
	{
		MainRow:     20,
		Name:        StrPtr("Magic Wand"),
		Info1:       StrPtr("Melee"),
		Info2:       StrPtr("Power E"),
		Info3:       StrPtr("Combo 3"),
		Description: StrPtr("Ceramic. Makes a sound."),
	},
	{
		MainRow:     21,
		Name:        StrPtr("Tessen"),
		Info1:       StrPtr("Melee"),
		Info2:       StrPtr("Power D"),
		Info3:       StrPtr("Combo 3"),
		Description: StrPtr("Carbon steel cutting edge."),
	},
	{
		MainRow:     22,
		Name:        StrPtr("Excalibur"),
		Info1:       StrPtr("Melee"),
		Info2:       StrPtr("Power A"),
		Info3:       StrPtr("Combo 3"),
		Description: StrPtr("Unwieldy titanium blade."),
	},
// Ammo 23-33
	{
		MainRow:     23,
		Name:        StrPtr("Amm.Arm MG"),
		Info1:       StrPtr("Ammo"),
		Info2:       StrPtr(""),
		Info3:       StrPtr(""),
		Description: StrPtr("20 round mag."),
	},
	{
		MainRow:     24,
		Name:        StrPtr("Amm.Needler"),
		Info1:       StrPtr("Ammo"),
		Info2:       StrPtr(""),
		Info3:       StrPtr(""),
		Description: StrPtr("10 charge mag."),
	},
	{
		MainRow:     25,
		Name:        StrPtr("Amm.HMG"),
		Info1:       StrPtr("Ammo"),
		Info2:       StrPtr(""),
		Info3:       StrPtr(""),
		Description: StrPtr("60 round double-mag."),
	},
	{
		MainRow:     26,
		Name:        StrPtr("Amm.Handgun"),
		Info1:       StrPtr("Ammo"),
		Info2:       StrPtr(""),
		Info3:       StrPtr(""),
		Description: StrPtr("10 round mag."),
	},
	{
		MainRow:     27,
		Name:        StrPtr("Amm.Sniper"),
		Info1:       StrPtr("Ammo"),
		Info2:       StrPtr(""),
		Info3:       StrPtr(""),
		Description: StrPtr("5 round mag."),
	},
	{
		MainRow:     28,
		Name:        StrPtr("Amm.SMG"),
		Info1:       StrPtr("Ammo"),
		Info2:       StrPtr(""),
		Info3:       StrPtr(""),
		Description: StrPtr("20 round mag."),
	},
	{
		MainRow:     29,
		Name:        StrPtr("Amm.Bazooka"),
		Info1:       StrPtr("Ammo"),
		Info2:       StrPtr(""),
		Info3:       StrPtr(""),
		Description: StrPtr("5 round mag."),
	},
	{
		MainRow:     30,
		Name:        StrPtr("Amm.Faust"),
		Info1:       StrPtr("Ammo"),
		Info2:       StrPtr(""),
		Info3:       StrPtr(""),
		Description: StrPtr("3 round mag."),
	},
	{
		MainRow:     31,
		Name:        StrPtr("Amm.Missile"),
		Info1:       StrPtr("Ammo"),
		Info2:       StrPtr(""),
		Info3:       StrPtr(""),
		Description: StrPtr("3 round mag."),
	},
	{
		MainRow:     32,
		Name:        StrPtr("Amm.Revolver"),
		Info1:       StrPtr("Ammo"),
		Info2:       StrPtr(""),
		Info3:       StrPtr(""),
		Description: StrPtr("6 round speedloader."),
	},
	{
		MainRow:     33,
		Name:        StrPtr("Amm.Shotgun"),
		Info1:       StrPtr("Ammo"),
		Info2:       StrPtr(""),
		Info3:       StrPtr(""),
		Description: StrPtr("7 shotgun rounds."),
	},
	{
// Outfits 34-50
		MainRow:     34,
		Name:        StrPtr("Maid"),
		Info1:       StrPtr("Outfit"),
		Info2:       StrPtr(""),
		Info3:       StrPtr(""),
		Description: StrPtr("Standard-issue maid outfit."),
	},
	{
		MainRow:     35,
		Name:        StrPtr("Santa"),
		Info1:       StrPtr("Outfit"),
		Info2:       StrPtr("Unequips"),
		Info3:       StrPtr("headwear."),
		Description: StrPtr("Christmas outfit. Includes hat."),
	},
	{
		MainRow:     36,
		Name:        StrPtr("Swimsuit"),
		Info1:       StrPtr("Outfit"),
		Info2:       StrPtr(""),
		Info3:       StrPtr(""),
		Description: StrPtr(""),
	},
	{
		MainRow:     37,
		Name:        StrPtr("Waitress"),
		Info1:       StrPtr("Outfit"),
		Info2:       StrPtr(""),
		Info3:       StrPtr(""),
		Description: StrPtr("Includes tray and waitress cap."),
	},
	{
		MainRow:     38,
		Name:        StrPtr("Gym Clothes"),
		Info1:       StrPtr("Outfit"),
		Info2:       StrPtr(""),
		Info3:       StrPtr(""),
		Description: StrPtr(""),
	},
	{
		MainRow:     39,
		Name:        StrPtr("Gothic Dress"),
		Info1:       StrPtr("Outfit"),
		Info2:       StrPtr(""),
		Info3:       StrPtr(""),
		Description: StrPtr("A handmade dress from Kimiko."),
	},
	{
		MainRow:     40,
		Name:        StrPtr("Magic Dress"),
		Info1:       StrPtr("Outfit"),
		Info2:       StrPtr("Unequips"),
		Info3:       StrPtr("headwear."),
		Description: StrPtr("Wizard outfit, with hat."),
	},
	{
		MainRow:     41,
		Name:        StrPtr("Military"),
		Info1:       StrPtr("Outfit"),
		Info2:       StrPtr(""),
		Info3:       StrPtr(""),
		Description: StrPtr("Camouflaged outfit with military boots."),
	},
	{
		MainRow:     42,
		Name:        StrPtr("Fantasy"),
		Info1:       StrPtr("Outfit"),
		Info2:       StrPtr("Unequips"),
		Info3:       StrPtr("headwear."),
		Description: StrPtr("A fantasy warrior outfit."),
	},
	{
		MainRow:     43,
		Name:        StrPtr("M. RED"),
		Info1:       StrPtr("Outfit"),
		Info2:       StrPtr(""),
		Info3:       StrPtr(""),
		Description: StrPtr("MIRAGE RED ~ A colorful outfit."),
	},
	{
		MainRow:     44,
		Name:        StrPtr("W. BLUE"),
		Info1:       StrPtr("Outfit"),
		Info2:       StrPtr(""),
		Info3:       StrPtr(""),
		Description: StrPtr("WONDER BLUE ~ A colorful outfit."),
	},
	{
		MainRow:     45,
		Name:        StrPtr("S. ORANGE"),
		Info1:       StrPtr("Outfit"),
		Info2:       StrPtr(""),
		Info3:       StrPtr(""),
		Description: StrPtr("STOIC ORANGE ~ A colorful outfit."),
	},
	{
		MainRow:     46,
		Name:        StrPtr("I. PURPLE"),
		Info1:       StrPtr("Outfit"),
		Info2:       StrPtr(""),
		Info3:       StrPtr(""),
		Description: StrPtr("ILLUSION PURPLE ~ A colorful outfit."),
	},
	{
		MainRow:     47,
		Name:        StrPtr("T. BLACK"),
		Info1:       StrPtr("Outfit"),
		Info2:       StrPtr(""),
		Info3:       StrPtr(""),
		Description: StrPtr("TURN BLACK ~ A colorful outfit."),
	},
	{
		MainRow:     48,
		Name:        StrPtr("Furisode"),
		Info1:       StrPtr("Outfit"),
		Info2:       StrPtr("Disables"),
		Info3:       StrPtr("missions."),
		Description: StrPtr("New Year's outfit. You can't play missions while wearing this."),
	},
	{
		MainRow:     49,
		Name:        StrPtr("Miko"),
		Info1:       StrPtr("Outfit"),
		Info2:       StrPtr(""),
		Info3:       StrPtr(""),
		Description: StrPtr("Includes onusa and bamboo broom."),
	},
	{
		MainRow:     50,
		Name:        StrPtr("Chinese"),
		Info1:       StrPtr("Outfit"),
		Info2:       StrPtr("Disables"),
		Info3:       StrPtr("missions."),
		Description: StrPtr("You can't play missions while wearing this."),
	},
	{
		MainRow:     51,
// Antennas & accessories 51-68
		Name:        StrPtr("Antenna"),
		Info1:       StrPtr("Antenna"),
		Info2:       StrPtr(""),
		Info3:       StrPtr(""),
		Description: StrPtr("Standard antenna."),
	},
	{
		MainRow:     52,
		Name:        StrPtr("Broom"),
		Info1:       StrPtr("Item"),
		Info2:       StrPtr(""),
		Info3:       StrPtr(""),
		Description: StrPtr("Cleaning broom."),
	},
	{
		MainRow:     53,
		Name:        StrPtr("Voice Kit"),
		Info1:       StrPtr("Antenna"),
		Info2:       StrPtr(""),
		Info3:       StrPtr(""),
		Description: StrPtr("Talking Hoihoi-san."),
	},
	{
		MainRow:     54,
		Name:        StrPtr("VK: Cool"),
		Info1:       StrPtr("Antenna"),
		Info2:       StrPtr(""),
		Info3:       StrPtr(""),
		Description: StrPtr("Cool voice."),
	},
	{
		MainRow:     55,
		Name:        StrPtr("VK: Onee-san"),
		Info1:       StrPtr("Antenna"),
		Info2:       StrPtr(""),
		Info3:       StrPtr(""),
		Description: StrPtr("Older sister voice."),
	},
	{
		MainRow:     56,
		Name:        StrPtr("VK: Kansai"),
		Info1:       StrPtr("Antenna"),
		Info2:       StrPtr(""),
		Info3:       StrPtr(""),
		Description: StrPtr("Kansai dialect."),
	},
	{
		MainRow:     57,
		Name:        StrPtr("VK: Heroine"),
		Info1:       StrPtr("Antenna"),
		Info2:       StrPtr(""),
		Info3:       StrPtr(""),
		Description: StrPtr("Heroine voice."),
	},
	{
		MainRow:     58,
		Name:        StrPtr("Analysystem"),
		Info1:       StrPtr("Antenna"),
		Info2:       StrPtr(""),
		Info3:       StrPtr(""),
		Description: StrPtr("Adds analysis function to check target state."),
	},
	{
		MainRow:     59,
		Name:        StrPtr("HVA System"),
		Info1:       StrPtr("Antenna"),
		Info2:       StrPtr(""),
		Info3:       StrPtr(""),
		Description: StrPtr("Hyper Vital Assist w/ Anti-Vibration and Analyze System."),
	},
	{
		MainRow:     60,
		Name:        StrPtr("Bat.pack S"),
		Info1:       StrPtr("Auxiliary"),
		Info2:       StrPtr(""),
		Info3:       StrPtr(""),
		Description: StrPtr("Backpack with 2 expansion batteries."),
	},
	{
		MainRow:     61,
		Name:        StrPtr("Bat.pack M"),
		Info1:       StrPtr("Auxiliary"),
		Info2:       StrPtr(""),
		Info3:       StrPtr(""),
		Description: StrPtr("Backpack with 4 expansion batteries."),
	},
	{
		MainRow:     62,
		Name:        StrPtr("Bat.pack L"),
		Info1:       StrPtr("Auxiliary"),
		Info2:       StrPtr(""),
		Info3:       StrPtr(""),
		Description: StrPtr("Backpack with 6 expansion batteries."),
	},
	{
		MainRow:     63,
		Name:        StrPtr("Desk Charger"),
		Info1:       StrPtr("Installed"),
		Info2:       StrPtr(""),
		Info3:       StrPtr(""),
		Description: StrPtr("Included charger dock."),
	},
	{
		MainRow:     64,
		Name:        StrPtr("Mobile Lift"),
		Info1:       StrPtr("Installed"),
		Info2:       StrPtr(""),
		Info3:       StrPtr(""),
		Description: StrPtr("Made of ABS; lightweight but strong."),
	},
	{
		MainRow:     65,
		Name:        StrPtr("Glasses"),
		Info1:       StrPtr("Accessory"),
		Info2:       StrPtr(""),
		Info3:       StrPtr(""),
		Description: StrPtr(""),
	},
	{
		MainRow:     66,
		Name:        StrPtr("Sunglasses"),
		Info1:       StrPtr("Accessory"),
		Info2:       StrPtr(""),
		Info3:       StrPtr(""),
		Description: StrPtr(""),
	},
	{
		MainRow:     67,
		Name:        StrPtr("Cat Ears"),
		Info1:       StrPtr("Accessory"),
		Info2:       StrPtr(""),
		Info3:       StrPtr(""),
		Description: StrPtr(""),
	},
	{
		MainRow:     68,
		Name:        StrPtr("Rabbit Ears"),
		Info1:       StrPtr("Accessory"),
		Info2:       StrPtr(""),
		Info3:       StrPtr(""),
		Description: StrPtr(""),
	},
	{
		MainRow:     69,
		Name:        StrPtr("Voice Player"),
// Treasures 69-71
		Info1:       StrPtr("Treasure"),
		Info2:       StrPtr(""),
		Info3:       StrPtr(""),
		Description: StrPtr("Play the voice of Talking Hoihoi-san at will."),
	},
	{
		MainRow:     70,
		Name:        StrPtr("Puzzle"),
		Info1:       StrPtr("Treasure"),
		Info2:       StrPtr(""),
		Info3:       StrPtr(""),
		Description: StrPtr("???"),
	},
	{
		MainRow:     71,
		Name:        StrPtr("Point Card"),
		Info1:       StrPtr("Treasure"),
		Info2:       StrPtr(""),
		Info3:       StrPtr(""),
		Description: StrPtr("Sticker sheet for pharmacy points."),
	},
	{
		MainRow:     72,
		Name:        StrPtr("Voice Kit"),
		Info1:       StrPtr("Press □"),
// Voice kits 72-76
		Info2:       StrPtr("to play"),
		Info3:       StrPtr("audio."),
		Description: StrPtr("Talking Hoihoi-san."),
	},
	{
		MainRow:     73,
		Name:        StrPtr("Voice (Cool)"),
		Info1:       StrPtr("Press □"),
		Info2:       StrPtr("to play"),
		Info3:       StrPtr("audio."),
		Description: StrPtr("Cool voice."),
	},
	{
		MainRow:     74,
		Name:        StrPtr("Voice (Onee-san)"),
		Info1:       StrPtr("Press □"),
		Info2:       StrPtr("to play"),
		Info3:       StrPtr("audio."),
		Description: StrPtr("Older sister voice."),
	},
	{
		MainRow:     75,
		Name:        StrPtr("Voice (Kansai)"),
		Info1:       StrPtr("Press □"),
		Info2:       StrPtr("to play"),
		Info3:       StrPtr("audio."),
		Description: StrPtr("Kansai dialect."),
	},
	{
		MainRow:     76,
		Name:        StrPtr("Voice (Heroine)"),
		Info1:       StrPtr("Press □"),
		Info2:       StrPtr("to play"),
		Info3:       StrPtr("audio."),
		Description: StrPtr("Heroine voice."),
	},
	{
		MainRow:     77,
		Name:        StrPtr("R Lift Bat."),
		Info1:       StrPtr("Installed"),
		Info2:       StrPtr("Enables"),
// Lift batteries 77-79
		Info3:       StrPtr("red lift."),
		Description: StrPtr("Battery for red Mobile Lift."),
	},
	{
		MainRow:     78,
		Name:        StrPtr("G Lift Bat."),
		Info1:       StrPtr("Installed"),
		Info2:       StrPtr("Enables"),
		Info3:       StrPtr("green lift."),
		Description: StrPtr("Battery for green Mobile Lift."),
	},
	{
		MainRow:     79,
		Name:        StrPtr("B Lift Bat."),
		Info1:       StrPtr("Installed"),
		Info2:       StrPtr("Enables"),
		Info3:       StrPtr("blue lift."),
		Description: StrPtr("Battery for blue Mobile Lift."),
	},
}
